//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voting.ECollecting.Shared.Core.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Voting.ECollecting.Shared.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string UserNotification_InformalReviewRequested {
            get {
                return ResourceManager.GetString("UserNotification.InformalReviewRequested", resourceCulture);
            }
        }
        
        public static string UserNotification_InformalReviewWithdrawn {
            get {
                return ResourceManager.GetString("UserNotification.InformalReviewWithdrawn", resourceCulture);
            }
        }
        
        public static string UserNotification_StateChanged {
            get {
                return ResourceManager.GetString("UserNotification.StateChanged", resourceCulture);
            }
        }
        
        public static string CollectionState_PreRecorded {
            get {
                return ResourceManager.GetString("CollectionState.PreRecorded", resourceCulture);
            }
        }
        
        public static string CollectionState_InPreparation {
            get {
                return ResourceManager.GetString("CollectionState.InPreparation", resourceCulture);
            }
        }
        
        public static string CollectionState_Withdrawn {
            get {
                return ResourceManager.GetString("CollectionState.Withdrawn", resourceCulture);
            }
        }
        
        public static string CollectionState_Submitted {
            get {
                return ResourceManager.GetString("CollectionState.Submitted", resourceCulture);
            }
        }
        
        public static string CollectionState_NotPassed {
            get {
                return ResourceManager.GetString("CollectionState.NotPassed", resourceCulture);
            }
        }
        
        public static string CollectionState_ReturnedForCorrection {
            get {
                return ResourceManager.GetString("CollectionState.ReturnedForCorrection", resourceCulture);
            }
        }
        
        public static string CollectionState_UnderReview {
            get {
                return ResourceManager.GetString("CollectionState.UnderReview", resourceCulture);
            }
        }
        
        public static string CollectionState_ReadyForRegistration {
            get {
                return ResourceManager.GetString("CollectionState.ReadyForRegistration", resourceCulture);
            }
        }
        
        public static string CollectionState_Registered {
            get {
                return ResourceManager.GetString("CollectionState.Registered", resourceCulture);
            }
        }
        
        public static string CollectionState_PreparingForCollection {
            get {
                return ResourceManager.GetString("CollectionState.PreparingForCollection", resourceCulture);
            }
        }
        
        public static string CollectionState_EnabledForCollection_Initiative {
            get {
                return ResourceManager.GetString("CollectionState.EnabledForCollection.Initiative", resourceCulture);
            }
        }
        
        public static string CollectionState_EnabledForCollection_Referendum {
            get {
                return ResourceManager.GetString("CollectionState.EnabledForCollection.Referendum", resourceCulture);
            }
        }
        
        public static string CollectionState_SignatureSheetsSubmitted {
            get {
                return ResourceManager.GetString("CollectionState.SignatureSheetsSubmitted", resourceCulture);
            }
        }
        
        public static string CollectionState_EndedCameAbout {
            get {
                return ResourceManager.GetString("CollectionState.EndedCameAbout", resourceCulture);
            }
        }
        
        public static string CollectionState_EndedCameNotAbout {
            get {
                return ResourceManager.GetString("CollectionState.EndedCameNotAbout", resourceCulture);
            }
        }
    }
}
