// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Voting.ECollecting.Shared.Migrations;

#nullable disable

namespace Voting.ECollecting.Admin.Adapter.Data.Migrations
{
    [DbContext(typeof(MigrationDataContext))]
    [Migration("20240711133619_AclImport")]
    partial class AclImport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.AccessControlListDoiEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bfs")
                        .HasColumnType("text");

                    b.Property<string>("Canton")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ImportStatisticId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ValidationErrors")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ImportStatisticId");

                    b.HasIndex("ParentId");

                    b.ToTable("AccessControlListDois");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.DecreeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CollectionEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CollectionStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DomainOfInfluenceType")
                        .HasColumnType("integer");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxElectronicSignatureCount")
                        .HasColumnType("integer");

                    b.Property<int>("MinSignatureCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Decrees");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.ImportStatisticEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DatasetsCountCreated")
                        .HasColumnType("integer");

                    b.Property<int>("DatasetsCountDeleted")
                        .HasColumnType("integer");

                    b.Property<int>("DatasetsCountUpdated")
                        .HasColumnType("integer");

                    b.Property<List<Guid>>("EntitiesWithValidationErrors")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<DateTime?>("FinishedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasValidationErrors")
                        .HasColumnType("boolean");

                    b.Property<int>("ImportRecordsCountTotal")
                        .HasColumnType("integer");

                    b.Property<string>("ImportStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImportType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsLatest")
                        .HasColumnType("boolean");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("TotalElapsedMilliseconds")
                        .HasColumnType("double precision");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ImportStatistics");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.AccessControlListDoiEntity", b =>
                {
                    b.HasOne("Voting.ECollecting.Shared.Domain.Entities.ImportStatisticEntity", "ImportStatistic")
                        .WithMany("AccessControlListDois")
                        .HasForeignKey("ImportStatisticId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Voting.ECollecting.Shared.Domain.Entities.AccessControlListDoiEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("AccessControlListDoiEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CreatedById")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedById")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByName")
                                .HasColumnType("text");

                            b1.HasKey("AccessControlListDoiEntityId");

                            b1.ToTable("AccessControlListDois");

                            b1.WithOwner()
                                .HasForeignKey("AccessControlListDoiEntityId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("ImportStatistic");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.DecreeEntity", b =>
                {
                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("DecreeEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CreatedById")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedById")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByName")
                                .HasColumnType("text");

                            b1.HasKey("DecreeEntityId");

                            b1.ToTable("Decrees");

                            b1.WithOwner()
                                .HasForeignKey("DecreeEntityId");
                        });

                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.IntegritySignature.IntegritySignatureInfo", "IntegritySignatureInfo", b1 =>
                        {
                            b1.Property<Guid>("DecreeEntityId")
                                .HasColumnType("uuid");

                            b1.Property<byte[]>("IntegritySignature")
                                .IsRequired()
                                .HasColumnType("bytea");

                            b1.Property<string>("IntegritySignatureKeyId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<byte>("IntegritySignatureVersion")
                                .HasColumnType("smallint");

                            b1.HasKey("DecreeEntityId");

                            b1.ToTable("Decrees");

                            b1.WithOwner()
                                .HasForeignKey("DecreeEntityId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("IntegritySignatureInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.ImportStatisticEntity", b =>
                {
                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("ImportStatisticEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CreatedById")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedById")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByName")
                                .HasColumnType("text");

                            b1.HasKey("ImportStatisticEntityId");

                            b1.ToTable("ImportStatistics");

                            b1.WithOwner()
                                .HasForeignKey("ImportStatisticEntityId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.AccessControlListDoiEntity", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.ImportStatisticEntity", b =>
                {
                    b.Navigation("AccessControlListDois");
                });
#pragma warning restore 612, 618
        }
    }
}
