// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Voting.ECollecting.Shared.Migrations;

#nullable disable

namespace Voting.ECollecting.Admin.Adapter.Data.Migrations
{
    [DbContext(typeof(MigrationDataContext))]
    [Migration("20240618070845_Decree")]
    partial class Decree
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.DecreeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CollectionEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CollectionStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DomainOfInfluenceType")
                        .HasColumnType("integer");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxElectronicSignatureCount")
                        .HasColumnType("integer");

                    b.Property<int>("MinSignatureCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Decrees");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.DecreeEntity", b =>
                {
                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("DecreeEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CreatedById")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedById")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByName")
                                .HasColumnType("text");

                            b1.HasKey("DecreeEntityId");

                            b1.ToTable("Decrees");

                            b1.WithOwner()
                                .HasForeignKey("DecreeEntityId");
                        });

                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.IntegritySignature.IntegritySignatureInfo", "IntegritySignatureInfo", b1 =>
                        {
                            b1.Property<Guid>("DecreeEntityId")
                                .HasColumnType("uuid");

                            b1.Property<byte[]>("IntegritySignature")
                                .IsRequired()
                                .HasColumnType("bytea");

                            b1.Property<string>("IntegritySignatureKeyId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<byte>("IntegritySignatureVersion")
                                .HasColumnType("smallint");

                            b1.HasKey("DecreeEntityId");

                            b1.ToTable("Decrees");

                            b1.WithOwner()
                                .HasForeignKey("DecreeEntityId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("IntegritySignatureInfo")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
