// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Voting.ECollecting.Shared.Migrations;

#nullable disable

namespace Voting.ECollecting.Admin.Adapter.Data.Migrations
{
    [DbContext(typeof(MigrationDataContext))]
    [Migration("20250407064325_CollectionModelChange")]
    partial class CollectionModelChange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.AccessControlListDoiEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bfs")
                        .HasColumnType("text");

                    b.Property<string>("Canton")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ECollectingEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("ECollectingMaxElectronicSignaturePercent")
                        .HasColumnType("integer");

                    b.Property<int>("ECollectingMinSignatureCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ImportStatisticId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ValidationErrors")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ImportStatisticId");

                    b.HasIndex("ParentId");

                    b.ToTable("AccessControlListDois");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.CollectionBaseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("LogoImage")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("LogoImageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SensitiveDataExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("SignatureSheetFile")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<bool>("SignatureSheetGenerated")
                        .HasColumnType("boolean");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CollectionBaseEntity");

                    b.HasDiscriminator<int>("Type").HasValue(0);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.CollectionCountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid");

                    b.Property<int>("ElectronicCitizenCount")
                        .HasColumnType("integer");

                    b.Property<int>("TotalCitizenCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId")
                        .IsUnique();

                    b.ToTable("CollectionCounts");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.DecreeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CollectionEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CollectionStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DomainOfInfluenceType")
                        .HasColumnType("integer");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxElectronicSignatureCount")
                        .HasColumnType("integer");

                    b.Property<int>("MinSignatureCount")
                        .HasColumnType("integer");

                    b.Property<string>("MunicipalityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Decrees");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.ImportStatisticEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DatasetsCountCreated")
                        .HasColumnType("integer");

                    b.Property<int>("DatasetsCountDeleted")
                        .HasColumnType("integer");

                    b.Property<int>("DatasetsCountUpdated")
                        .HasColumnType("integer");

                    b.Property<List<Guid>>("EntitiesWithValidationErrors")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<DateTime?>("FinishedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasValidationErrors")
                        .HasColumnType("boolean");

                    b.Property<int>("ImportRecordsCountTotal")
                        .HasColumnType("integer");

                    b.Property<string>("ImportStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImportType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsLatest")
                        .HasColumnType("boolean");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("TotalElapsedMilliseconds")
                        .HasColumnType("double precision");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ImportStatistics");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.InitiativeEntity", b =>
                {
                    b.HasBaseType("Voting.ECollecting.Shared.Domain.Entities.CollectionBaseEntity");

                    b.Property<DateTime?>("CollectionEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CollectionStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DomainOfInfluenceType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsElectronicSubmission")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxElectronicSignatureCount")
                        .HasColumnType("integer");

                    b.Property<int>("MinSignatureCount")
                        .HasColumnType("integer");

                    b.Property<string>("MunicipalityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Wording")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.ReferendumEntity", b =>
                {
                    b.HasBaseType("Voting.ECollecting.Shared.Domain.Entities.CollectionBaseEntity");

                    b.Property<Guid?>("DecreeId")
                        .HasColumnType("uuid");

                    b.Property<string>("MembersCommittee")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("DecreeId");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.AccessControlListDoiEntity", b =>
                {
                    b.HasOne("Voting.ECollecting.Shared.Domain.Entities.ImportStatisticEntity", "ImportStatistic")
                        .WithMany("AccessControlListDois")
                        .HasForeignKey("ImportStatisticId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Voting.ECollecting.Shared.Domain.Entities.AccessControlListDoiEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("AccessControlListDoiEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CreatedById")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedById")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByName")
                                .HasColumnType("text");

                            b1.HasKey("AccessControlListDoiEntityId");

                            b1.ToTable("AccessControlListDois");

                            b1.WithOwner()
                                .HasForeignKey("AccessControlListDoiEntityId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("ImportStatistic");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.CollectionBaseEntity", b =>
                {
                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("CollectionBaseEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CreatedById")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedById")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByName")
                                .HasColumnType("text");

                            b1.HasKey("CollectionBaseEntityId");

                            b1.ToTable("CollectionBaseEntity");

                            b1.WithOwner()
                                .HasForeignKey("CollectionBaseEntityId");
                        });

                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.IntegritySignature.IntegritySignatureInfo", "IntegritySignatureInfo", b1 =>
                        {
                            b1.Property<Guid>("CollectionBaseEntityId")
                                .HasColumnType("uuid");

                            b1.Property<byte[]>("IntegritySignature")
                                .IsRequired()
                                .HasColumnType("bytea");

                            b1.Property<string>("IntegritySignatureKeyId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<byte>("IntegritySignatureVersion")
                                .HasColumnType("smallint");

                            b1.HasKey("CollectionBaseEntityId");

                            b1.ToTable("CollectionBaseEntity");

                            b1.WithOwner()
                                .HasForeignKey("CollectionBaseEntityId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("IntegritySignatureInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.CollectionCountEntity", b =>
                {
                    b.HasOne("Voting.ECollecting.Shared.Domain.Entities.CollectionBaseEntity", "Collection")
                        .WithOne("CollectionCount")
                        .HasForeignKey("Voting.ECollecting.Shared.Domain.Entities.CollectionCountEntity", "CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("CollectionCountEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CreatedById")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedById")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByName")
                                .HasColumnType("text");

                            b1.HasKey("CollectionCountEntityId");

                            b1.ToTable("CollectionCounts");

                            b1.WithOwner()
                                .HasForeignKey("CollectionCountEntityId");
                        });

                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.IntegritySignature.IntegritySignatureInfo", "IntegritySignatureInfo", b1 =>
                        {
                            b1.Property<Guid>("CollectionCountEntityId")
                                .HasColumnType("uuid");

                            b1.Property<byte[]>("IntegritySignature")
                                .IsRequired()
                                .HasColumnType("bytea");

                            b1.Property<string>("IntegritySignatureKeyId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<byte>("IntegritySignatureVersion")
                                .HasColumnType("smallint");

                            b1.HasKey("CollectionCountEntityId");

                            b1.ToTable("CollectionCounts");

                            b1.WithOwner()
                                .HasForeignKey("CollectionCountEntityId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("IntegritySignatureInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.DecreeEntity", b =>
                {
                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("DecreeEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CreatedById")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedById")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByName")
                                .HasColumnType("text");

                            b1.HasKey("DecreeEntityId");

                            b1.ToTable("Decrees");

                            b1.WithOwner()
                                .HasForeignKey("DecreeEntityId");
                        });

                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.IntegritySignature.IntegritySignatureInfo", "IntegritySignatureInfo", b1 =>
                        {
                            b1.Property<Guid>("DecreeEntityId")
                                .HasColumnType("uuid");

                            b1.Property<byte[]>("IntegritySignature")
                                .IsRequired()
                                .HasColumnType("bytea");

                            b1.Property<string>("IntegritySignatureKeyId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<byte>("IntegritySignatureVersion")
                                .HasColumnType("smallint");

                            b1.HasKey("DecreeEntityId");

                            b1.ToTable("Decrees");

                            b1.WithOwner()
                                .HasForeignKey("DecreeEntityId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("IntegritySignatureInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.ImportStatisticEntity", b =>
                {
                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("ImportStatisticEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CreatedById")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedById")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByName")
                                .HasColumnType("text");

                            b1.HasKey("ImportStatisticEntityId");

                            b1.ToTable("ImportStatistics");

                            b1.WithOwner()
                                .HasForeignKey("ImportStatisticEntityId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.ReferendumEntity", b =>
                {
                    b.HasOne("Voting.ECollecting.Shared.Domain.Entities.DecreeEntity", "Decree")
                        .WithMany("Collections")
                        .HasForeignKey("DecreeId");

                    b.Navigation("Decree");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.AccessControlListDoiEntity", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.CollectionBaseEntity", b =>
                {
                    b.Navigation("CollectionCount")
                        .IsRequired();
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.DecreeEntity", b =>
                {
                    b.Navigation("Collections");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.ImportStatisticEntity", b =>
                {
                    b.Navigation("AccessControlListDois");
                });
#pragma warning restore 612, 618
        }
    }
}
