// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Voting.ECollecting.Shared.Migrations;

#nullable disable

namespace Voting.ECollecting.Admin.Adapter.Data.Migrations
{
    [DbContext(typeof(MigrationDataContext))]
    [Migration("20250430150601_AddAuditInfoEmail")]
    partial class AddAuditInfoEmail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.AccessControlListDoiEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bfs")
                        .HasColumnType("text");

                    b.Property<string>("Canton")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ECollectingEnabled")
                        .HasColumnType("boolean");

                    b.Property<int?>("ECollectingInitiativeMaxElectronicSignaturePercent")
                        .HasColumnType("integer");

                    b.Property<int?>("ECollectingInitiativeMinSignatureCount")
                        .HasColumnType("integer");

                    b.Property<int?>("ECollectingInitiativeNumberOfMembersCommittee")
                        .HasColumnType("integer");

                    b.Property<int?>("ECollectingReferendumMaxElectronicSignaturePercent")
                        .HasColumnType("integer");

                    b.Property<int?>("ECollectingReferendumMinSignatureCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ImportStatisticId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ValidationErrors")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ImportStatisticId");

                    b.HasIndex("ParentId");

                    b.ToTable("AccessControlListDois");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.CollectionBaseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressCommittee")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("LogoImage")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("LogoImageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SensitiveDataExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("SignatureSheetFile")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<bool>("SignatureSheetGenerated")
                        .HasColumnType("boolean");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Collections");

                    b.HasDiscriminator<int>("Type").HasValue(0);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.CollectionCountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid");

                    b.Property<int>("ElectronicCitizenCount")
                        .HasColumnType("integer");

                    b.Property<int>("TotalCitizenCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId")
                        .IsUnique();

                    b.ToTable("CollectionCounts");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.CollectionMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("InitiativeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReferendumId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeId");

                    b.HasIndex("ReferendumId");

                    b.ToTable("CollectionMessages");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.DecreeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CollectionEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CollectionStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DomainOfInfluenceType")
                        .HasColumnType("integer");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxElectronicSignatureCount")
                        .HasColumnType("integer");

                    b.Property<int>("MinSignatureCount")
                        .HasColumnType("integer");

                    b.Property<string>("MunicipalityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Decrees");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.ImportStatisticEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DatasetsCountCreated")
                        .HasColumnType("integer");

                    b.Property<int>("DatasetsCountDeleted")
                        .HasColumnType("integer");

                    b.Property<int>("DatasetsCountUpdated")
                        .HasColumnType("integer");

                    b.Property<List<Guid>>("EntitiesWithValidationErrors")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<DateTime?>("FinishedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasValidationErrors")
                        .HasColumnType("boolean");

                    b.Property<int>("ImportRecordsCountTotal")
                        .HasColumnType("integer");

                    b.Property<string>("ImportStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImportType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsLatest")
                        .HasColumnType("boolean");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("TotalElapsedMilliseconds")
                        .HasColumnType("double precision");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ImportStatistics");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.InitiativeSubTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DomainOfInfluenceType")
                        .HasColumnType("integer");

                    b.Property<int>("MaxElectronicSignatureCount")
                        .HasColumnType("integer");

                    b.Property<int>("MinSignatureCount")
                        .HasColumnType("integer");

                    b.Property<string>("MunicipalityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InitiativeSubTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8926f191-6ba3-475f-9db0-d599b3317358"),
                            Description = "Verfassungsinitiative",
                            DomainOfInfluenceType = 2,
                            MaxElectronicSignatureCount = 4000,
                            MinSignatureCount = 8000,
                            MunicipalityId = "3200"
                        },
                        new
                        {
                            Id = new Guid("9bcaba6c-bc1b-43d6-a59e-620ac2f4872a"),
                            Description = "Gesetzesinitiative",
                            DomainOfInfluenceType = 2,
                            MaxElectronicSignatureCount = 3000,
                            MinSignatureCount = 6000,
                            MunicipalityId = "3200"
                        },
                        new
                        {
                            Id = new Guid("abd22fb4-f5d9-463b-8605-edfc0d93a6a3"),
                            Description = "Einheitsinitiative",
                            DomainOfInfluenceType = 2,
                            MaxElectronicSignatureCount = 2000,
                            MinSignatureCount = 4000,
                            MunicipalityId = "3200"
                        },
                        new
                        {
                            Id = new Guid("d0c38ef9-0619-4fdc-a859-237bf6f6d1d3"),
                            Description = "Volksinitiative",
                            DomainOfInfluenceType = 1,
                            MaxElectronicSignatureCount = 50000,
                            MinSignatureCount = 100000,
                            MunicipalityId = ""
                        });
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.UserNotificationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("FailureCounter")
                        .HasColumnType("integer");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<string>("RecipientEMail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SentTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("State");

                    b.ToTable("UserNotifications");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.InitiativeEntity", b =>
                {
                    b.HasBaseType("Voting.ECollecting.Shared.Domain.Entities.CollectionBaseEntity");

                    b.Property<DateTime?>("CollectionEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CollectionStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DomainOfInfluenceType")
                        .HasColumnType("integer");

                    b.Property<string>("GovernmentDecisionNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsElectronicSubmission")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxElectronicSignatureCount")
                        .HasColumnType("integer");

                    b.Property<int>("MinSignatureCount")
                        .HasColumnType("integer");

                    b.Property<string>("MunicipalityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SubTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Wording")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("SubTypeId");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.ReferendumEntity", b =>
                {
                    b.HasBaseType("Voting.ECollecting.Shared.Domain.Entities.CollectionBaseEntity");

                    b.Property<Guid?>("DecreeId")
                        .HasColumnType("uuid");

                    b.Property<string>("MembersCommittee")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("DecreeId");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.AccessControlListDoiEntity", b =>
                {
                    b.HasOne("Voting.ECollecting.Shared.Domain.Entities.ImportStatisticEntity", "ImportStatistic")
                        .WithMany("AccessControlListDois")
                        .HasForeignKey("ImportStatisticId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Voting.ECollecting.Shared.Domain.Entities.AccessControlListDoiEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("AccessControlListDoiEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CreatedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("CreatedById")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedById")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByName")
                                .HasColumnType("text");

                            b1.HasKey("AccessControlListDoiEntityId");

                            b1.ToTable("AccessControlListDois");

                            b1.WithOwner()
                                .HasForeignKey("AccessControlListDoiEntityId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("ImportStatistic");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.CollectionBaseEntity", b =>
                {
                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("CollectionBaseEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CreatedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("CreatedById")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedById")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByName")
                                .HasColumnType("text");

                            b1.HasKey("CollectionBaseEntityId");

                            b1.ToTable("Collections");

                            b1.WithOwner()
                                .HasForeignKey("CollectionBaseEntityId");
                        });

                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.IntegritySignature.IntegritySignatureInfo", "IntegritySignatureInfo", b1 =>
                        {
                            b1.Property<Guid>("CollectionBaseEntityId")
                                .HasColumnType("uuid");

                            b1.Property<byte[]>("IntegritySignature")
                                .IsRequired()
                                .HasColumnType("bytea");

                            b1.Property<string>("IntegritySignatureKeyId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<byte>("IntegritySignatureVersion")
                                .HasColumnType("smallint");

                            b1.HasKey("CollectionBaseEntityId");

                            b1.ToTable("Collections");

                            b1.WithOwner()
                                .HasForeignKey("CollectionBaseEntityId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("IntegritySignatureInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.CollectionCountEntity", b =>
                {
                    b.HasOne("Voting.ECollecting.Shared.Domain.Entities.CollectionBaseEntity", "Collection")
                        .WithOne("CollectionCount")
                        .HasForeignKey("Voting.ECollecting.Shared.Domain.Entities.CollectionCountEntity", "CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("CollectionCountEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CreatedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("CreatedById")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedById")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByName")
                                .HasColumnType("text");

                            b1.HasKey("CollectionCountEntityId");

                            b1.ToTable("CollectionCounts");

                            b1.WithOwner()
                                .HasForeignKey("CollectionCountEntityId");
                        });

                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.IntegritySignature.IntegritySignatureInfo", "IntegritySignatureInfo", b1 =>
                        {
                            b1.Property<Guid>("CollectionCountEntityId")
                                .HasColumnType("uuid");

                            b1.Property<byte[]>("IntegritySignature")
                                .IsRequired()
                                .HasColumnType("bytea");

                            b1.Property<string>("IntegritySignatureKeyId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<byte>("IntegritySignatureVersion")
                                .HasColumnType("smallint");

                            b1.HasKey("CollectionCountEntityId");

                            b1.ToTable("CollectionCounts");

                            b1.WithOwner()
                                .HasForeignKey("CollectionCountEntityId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("IntegritySignatureInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.CollectionMessageEntity", b =>
                {
                    b.HasOne("Voting.ECollecting.Shared.Domain.Entities.InitiativeEntity", "Initiative")
                        .WithMany("Messages")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Voting.ECollecting.Shared.Domain.Entities.ReferendumEntity", "Referendum")
                        .WithMany("Messages")
                        .HasForeignKey("ReferendumId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("CollectionMessageEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CreatedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("CreatedById")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedById")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByName")
                                .HasColumnType("text");

                            b1.HasKey("CollectionMessageEntityId");

                            b1.ToTable("CollectionMessages");

                            b1.WithOwner()
                                .HasForeignKey("CollectionMessageEntityId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("Initiative");

                    b.Navigation("Referendum");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.DecreeEntity", b =>
                {
                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("DecreeEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CreatedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("CreatedById")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedById")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByName")
                                .HasColumnType("text");

                            b1.HasKey("DecreeEntityId");

                            b1.ToTable("Decrees");

                            b1.WithOwner()
                                .HasForeignKey("DecreeEntityId");
                        });

                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.IntegritySignature.IntegritySignatureInfo", "IntegritySignatureInfo", b1 =>
                        {
                            b1.Property<Guid>("DecreeEntityId")
                                .HasColumnType("uuid");

                            b1.Property<byte[]>("IntegritySignature")
                                .IsRequired()
                                .HasColumnType("bytea");

                            b1.Property<string>("IntegritySignatureKeyId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<byte>("IntegritySignatureVersion")
                                .HasColumnType("smallint");

                            b1.HasKey("DecreeEntityId");

                            b1.ToTable("Decrees");

                            b1.WithOwner()
                                .HasForeignKey("DecreeEntityId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("IntegritySignatureInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.ImportStatisticEntity", b =>
                {
                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("ImportStatisticEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CreatedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("CreatedById")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedById")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByName")
                                .HasColumnType("text");

                            b1.HasKey("ImportStatisticEntityId");

                            b1.ToTable("ImportStatistics");

                            b1.WithOwner()
                                .HasForeignKey("ImportStatisticEntityId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.UserNotificationEntity", b =>
                {
                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.UserNotificationTemplateBag", "TemplateBag", b1 =>
                        {
                            b1.Property<Guid>("UserNotificationEntityId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CollectionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CollectionName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("CollectionType")
                                .HasColumnType("integer");

                            b1.Property<int>("NotificationType")
                                .HasColumnType("integer");

                            b1.Property<bool>("RecipientIsCitizen")
                                .HasColumnType("boolean");

                            b1.HasKey("UserNotificationEntityId");

                            b1.ToTable("UserNotifications");

                            b1.WithOwner()
                                .HasForeignKey("UserNotificationEntityId");
                        });

                    b.Navigation("TemplateBag")
                        .IsRequired();
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.InitiativeEntity", b =>
                {
                    b.HasOne("Voting.ECollecting.Shared.Domain.Entities.InitiativeSubTypeEntity", "SubType")
                        .WithMany()
                        .HasForeignKey("SubTypeId");

                    b.Navigation("SubType");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.ReferendumEntity", b =>
                {
                    b.HasOne("Voting.ECollecting.Shared.Domain.Entities.DecreeEntity", "Decree")
                        .WithMany("Collections")
                        .HasForeignKey("DecreeId");

                    b.Navigation("Decree");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.AccessControlListDoiEntity", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.CollectionBaseEntity", b =>
                {
                    b.Navigation("CollectionCount")
                        .IsRequired();
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.DecreeEntity", b =>
                {
                    b.Navigation("Collections");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.ImportStatisticEntity", b =>
                {
                    b.Navigation("AccessControlListDois");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.InitiativeEntity", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.ReferendumEntity", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
