// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Voting.ECollecting.Shared.Migrations;

#nullable disable

namespace Voting.ECollecting.Admin.Adapter.Data.Migrations
{
    [DbContext(typeof(MigrationDataContext))]
    [Migration("20251119094611_MoveSensitiveDataExpiryDateToDecreeAndInitiative")]
    partial class MoveSensitiveDataExpiryDateToDecreeAndInitiative
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.AccessControlListDoiEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bfs")
                        .HasColumnType("text");

                    b.Property<string>("Canton")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ECollectingEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ECollectingEnabled")
                        .HasColumnType("boolean");

                    b.Property<int?>("ECollectingInitiativeMaxElectronicSignaturePercent")
                        .HasColumnType("integer");

                    b.Property<int?>("ECollectingInitiativeMinSignatureCount")
                        .HasColumnType("integer");

                    b.Property<int?>("ECollectingInitiativeNumberOfMembersCommittee")
                        .HasColumnType("integer");

                    b.Property<int?>("ECollectingReferendumMaxElectronicSignaturePercent")
                        .HasColumnType("integer");

                    b.Property<int?>("ECollectingReferendumMinSignatureCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ImportStatisticId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsValid")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameForProtocol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortNumber")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ValidationErrors")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ImportStatisticId");

                    b.HasIndex("ParentId");

                    b.ToTable("AccessControlListDois");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.CertificateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContentId")
                        .IsUnique();

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.CollectionBaseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bfs")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CollectionEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CollectionStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DomainOfInfluenceType")
                        .HasColumnType("integer");

                    b.Property<string>("EncryptionKeyId")
                        .HasColumnType("text");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uuid");

                    b.Property<bool>("InformalReviewRequested")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsElectronicSubmission")
                        .HasColumnType("boolean");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("LogoId")
                        .HasColumnType("uuid");

                    b.Property<string>("MacKeyId")
                        .HasColumnType("text");

                    b.Property<int?>("MaxElectronicSignatureCount")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SignatureSheetTemplateGenerated")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("SignatureSheetTemplateId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ImageId")
                        .IsUnique();

                    b.HasIndex("LogoId")
                        .IsUnique();

                    b.HasIndex("SignatureSheetTemplateId")
                        .IsUnique();

                    b.ToTable("Collections");

                    b.HasDiscriminator<int>("Type").HasValue(0);

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.CollectionCitizenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CollectionDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CollectionMunicipalityId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sex")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SignatureSheetId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CollectionMunicipalityId");

                    b.HasIndex("SignatureSheetId");

                    b.ToTable("CollectionCitizens");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.CollectionCitizenLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionCitizenId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DecreeEntityId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("VotingStimmregisterIdEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("VotingStimmregisterIdMac")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("CollectionCitizenId")
                        .IsUnique();

                    b.HasIndex("DecreeEntityId");

                    b.HasIndex("CollectionId", "VotingStimmregisterIdMac")
                        .IsUnique();

                    b.ToTable("CollectionCitizenLogs");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.CollectionCountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid");

                    b.Property<int>("ElectronicCitizenCount")
                        .HasColumnType("integer");

                    b.Property<int>("TotalCitizenCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId")
                        .IsUnique();

                    b.ToTable("CollectionCounts");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.CollectionMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.ToTable("CollectionMessages");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.CollectionMunicipalityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bfs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid");

                    b.Property<int>("ElectronicCitizenCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<string>("MunicipalityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NextSheetNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId", "Bfs")
                        .IsUnique();

                    b.ToTable("CollectionMunicipalities");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.CollectionPermissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IamFirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IamLastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IamUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("InitiativeCommitteeMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InitiativeCommitteeMemberId")
                        .IsUnique();

                    b.HasIndex("CollectionId", "Email")
                        .IsUnique();

                    b.ToTable("CollectionPermissions");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.CollectionSignatureSheetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AttestedAt")
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone");

                    b.Property<Guid>("CollectionMunicipalityId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSample")
                        .HasColumnType("boolean");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CollectionMunicipalityId", "Number")
                        .IsUnique();

                    b.ToTable("CollectionSignatureSheets");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.DecreeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bfs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CameNotAboutReason")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CollectionEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CollectionStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DomainOfInfluenceType")
                        .HasColumnType("integer");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxElectronicSignatureCount")
                        .HasColumnType("integer");

                    b.Property<int>("MinSignatureCount")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("SensitiveDataExpiryDate")
                        .HasColumnType("date");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Decrees");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.DomainOfInfluenceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bfs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("LogoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Webpage")
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Bfs")
                        .IsUnique();

                    b.HasIndex("LogoId")
                        .IsUnique();

                    b.ToTable("DomainOfInfluences");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.FileContentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.ToTable("FileContents");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.FileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CommitteeListOfInitiativeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CommitteeListOfInitiativeId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.ImportStatisticEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DatasetsCountCreated")
                        .HasColumnType("integer");

                    b.Property<int>("DatasetsCountDeleted")
                        .HasColumnType("integer");

                    b.Property<int>("DatasetsCountUpdated")
                        .HasColumnType("integer");

                    b.Property<List<Guid>>("EntitiesWithValidationErrors")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<DateTime?>("FinishedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasValidationErrors")
                        .HasColumnType("boolean");

                    b.Property<int>("ImportRecordsCountTotal")
                        .HasColumnType("integer");

                    b.Property<string>("ImportStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImportType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsLatest")
                        .HasColumnType("boolean");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("TotalElapsedMilliseconds")
                        .HasColumnType("double precision");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ImportStatistics");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.InitiativeCommitteeMemberEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ApprovalState")
                        .HasColumnType("integer");

                    b.Property<string>("Bfs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IamUserId")
                        .HasColumnType("text");

                    b.Property<Guid>("InitiativeId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("MemberSignatureRequested")
                        .HasColumnType("boolean");

                    b.Property<string>("PoliticalBfs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PoliticalDuty")
                        .HasColumnType("text");

                    b.Property<string>("PoliticalFirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PoliticalLastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SignatureFileId")
                        .HasColumnType("uuid");

                    b.Property<int>("SignatureType")
                        .HasColumnType("integer");

                    b.Property<int>("SortIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SignatureFileId")
                        .IsUnique();

                    b.HasIndex("InitiativeId", "SortIndex");

                    b.ToTable("InitiativeCommitteeMembers");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.InitiativeSubTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bfs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DomainOfInfluenceType")
                        .HasColumnType("integer");

                    b.Property<int>("MaxElectronicSignatureCount")
                        .HasColumnType("integer");

                    b.Property<int>("MinSignatureCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("InitiativeSubTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8926f191-6ba3-475f-9db0-d599b3317358"),
                            Bfs = "3200",
                            Description = "Verfassungsinitiative",
                            DomainOfInfluenceType = 2,
                            MaxElectronicSignatureCount = 4000,
                            MinSignatureCount = 8000
                        },
                        new
                        {
                            Id = new Guid("9bcaba6c-bc1b-43d6-a59e-620ac2f4872a"),
                            Bfs = "3200",
                            Description = "Gesetzesinitiative",
                            DomainOfInfluenceType = 2,
                            MaxElectronicSignatureCount = 3000,
                            MinSignatureCount = 6000
                        },
                        new
                        {
                            Id = new Guid("abd22fb4-f5d9-463b-8605-edfc0d93a6a3"),
                            Bfs = "3200",
                            Description = "Einheitsinitiative",
                            DomainOfInfluenceType = 2,
                            MaxElectronicSignatureCount = 2000,
                            MinSignatureCount = 4000
                        },
                        new
                        {
                            Id = new Guid("d0c38ef9-0619-4fdc-a859-237bf6f6d1d3"),
                            Bfs = "",
                            Description = "Volksinitiative",
                            DomainOfInfluenceType = 1,
                            MaxElectronicSignatureCount = 50000,
                            MinSignatureCount = 100000
                        });
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.SecondFactorTransactionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionIdHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<string>>("ExternalTokenJwtIds")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PollCount")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SecondFactorTransactions");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.UserNotificationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("FailureCounter")
                        .HasColumnType("integer");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<string>("RecipientEMail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SentTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("State");

                    b.ToTable("UserNotifications");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.InitiativeEntity", b =>
                {
                    b.HasBaseType("Voting.ECollecting.Shared.Domain.Entities.CollectionBaseEntity");

                    b.Property<int?>("AdmissibilityDecisionState")
                        .HasColumnType("integer");

                    b.Property<int?>("CameNotAboutReason")
                        .HasColumnType("integer");

                    b.Property<string>("GovernmentDecisionNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MinSignatureCount")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("SensitiveDataExpiryDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("SubTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Wording")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("SubTypeId");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.ReferendumEntity", b =>
                {
                    b.HasBaseType("Voting.ECollecting.Shared.Domain.Entities.CollectionBaseEntity");

                    b.Property<Guid?>("DecreeId")
                        .HasColumnType("uuid");

                    b.Property<string>("MembersCommittee")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("DecreeId");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.AccessControlListDoiEntity", b =>
                {
                    b.HasOne("Voting.ECollecting.Shared.Domain.Entities.ImportStatisticEntity", "ImportStatistic")
                        .WithMany("AccessControlListDois")
                        .HasForeignKey("ImportStatisticId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Voting.ECollecting.Shared.Domain.Entities.AccessControlListDoiEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("AccessControlListDoiEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CreatedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("CreatedById")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedById")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByName")
                                .HasColumnType("text");

                            b1.HasKey("AccessControlListDoiEntityId");

                            b1.ToTable("AccessControlListDois");

                            b1.WithOwner()
                                .HasForeignKey("AccessControlListDoiEntityId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("ImportStatistic");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.CertificateEntity", b =>
                {
                    b.HasOne("Voting.ECollecting.Shared.Domain.Entities.FileEntity", "Content")
                        .WithOne("ContentOfCertificate")
                        .HasForeignKey("Voting.ECollecting.Shared.Domain.Entities.CertificateEntity", "ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("CertificateEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CreatedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("CreatedById")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedById")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByName")
                                .HasColumnType("text");

                            b1.HasKey("CertificateEntityId");

                            b1.ToTable("Certificates");

                            b1.WithOwner()
                                .HasForeignKey("CertificateEntityId");
                        });

                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.CertificateInfo", "CAInfo", b1 =>
                        {
                            b1.Property<Guid>("CertificateEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("NotAfter")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("NotBefore")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Subject")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Thumbprint")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("CertificateEntityId");

                            b1.ToTable("Certificates");

                            b1.WithOwner()
                                .HasForeignKey("CertificateEntityId");
                        });

                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.CertificateInfo", "Info", b1 =>
                        {
                            b1.Property<Guid>("CertificateEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("NotAfter")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTime>("NotBefore")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Subject")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Thumbprint")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("CertificateEntityId");

                            b1.ToTable("Certificates");

                            b1.WithOwner()
                                .HasForeignKey("CertificateEntityId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("CAInfo");

                    b.Navigation("Content");

                    b.Navigation("Info");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.CollectionBaseEntity", b =>
                {
                    b.HasOne("Voting.ECollecting.Shared.Domain.Entities.FileEntity", "Image")
                        .WithOne("ImageOfCollection")
                        .HasForeignKey("Voting.ECollecting.Shared.Domain.Entities.CollectionBaseEntity", "ImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Voting.ECollecting.Shared.Domain.Entities.FileEntity", "Logo")
                        .WithOne("LogoOfCollection")
                        .HasForeignKey("Voting.ECollecting.Shared.Domain.Entities.CollectionBaseEntity", "LogoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Voting.ECollecting.Shared.Domain.Entities.FileEntity", "SignatureSheetTemplate")
                        .WithOne("SignatureSheetOfCollection")
                        .HasForeignKey("Voting.ECollecting.Shared.Domain.Entities.CollectionBaseEntity", "SignatureSheetTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.CollectionAddress", "Address", b1 =>
                        {
                            b1.Property<Guid>("CollectionBaseEntityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CommitteeOrPerson")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Locality")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("StreetOrPostOfficeBox")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("CollectionBaseEntityId");

                            b1.ToTable("Collections");

                            b1.WithOwner()
                                .HasForeignKey("CollectionBaseEntityId");
                        });

                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("CollectionBaseEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CreatedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("CreatedById")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedById")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByName")
                                .HasColumnType("text");

                            b1.HasKey("CollectionBaseEntityId");

                            b1.ToTable("Collections");

                            b1.WithOwner()
                                .HasForeignKey("CollectionBaseEntityId");
                        });

                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.IntegritySignature.IntegritySignatureInfo", "IntegritySignatureInfo", b1 =>
                        {
                            b1.Property<Guid>("CollectionBaseEntityId")
                                .HasColumnType("uuid");

                            b1.Property<byte[]>("IntegritySignature")
                                .IsRequired()
                                .HasColumnType("bytea");

                            b1.Property<string>("IntegritySignatureKeyId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<byte>("IntegritySignatureVersion")
                                .HasColumnType("smallint");

                            b1.HasKey("CollectionBaseEntityId");

                            b1.ToTable("Collections");

                            b1.WithOwner()
                                .HasForeignKey("CollectionBaseEntityId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("IntegritySignatureInfo")
                        .IsRequired();

                    b.Navigation("Logo");

                    b.Navigation("SignatureSheetTemplate");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.CollectionCitizenEntity", b =>
                {
                    b.HasOne("Voting.ECollecting.Shared.Domain.Entities.CollectionMunicipalityEntity", "CollectionMunicipality")
                        .WithMany("Citizens")
                        .HasForeignKey("CollectionMunicipalityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Voting.ECollecting.Shared.Domain.Entities.CollectionSignatureSheetEntity", "SignatureSheet")
                        .WithMany("Citizens")
                        .HasForeignKey("SignatureSheetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("CollectionCitizenEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CreatedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("CreatedById")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedById")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByName")
                                .HasColumnType("text");

                            b1.HasKey("CollectionCitizenEntityId");

                            b1.ToTable("CollectionCitizens");

                            b1.WithOwner()
                                .HasForeignKey("CollectionCitizenEntityId");
                        });

                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.IntegritySignature.IntegritySignatureInfo", "IntegritySignatureInfo", b1 =>
                        {
                            b1.Property<Guid>("CollectionCitizenEntityId")
                                .HasColumnType("uuid");

                            b1.Property<byte[]>("IntegritySignature")
                                .IsRequired()
                                .HasColumnType("bytea");

                            b1.Property<string>("IntegritySignatureKeyId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<byte>("IntegritySignatureVersion")
                                .HasColumnType("smallint");

                            b1.HasKey("CollectionCitizenEntityId");

                            b1.ToTable("CollectionCitizens");

                            b1.WithOwner()
                                .HasForeignKey("CollectionCitizenEntityId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("CollectionMunicipality");

                    b.Navigation("IntegritySignatureInfo")
                        .IsRequired();

                    b.Navigation("SignatureSheet");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.CollectionCitizenLogEntity", b =>
                {
                    b.HasOne("Voting.ECollecting.Shared.Domain.Entities.CollectionCitizenEntity", "CollectionCitizen")
                        .WithOne("Log")
                        .HasForeignKey("Voting.ECollecting.Shared.Domain.Entities.CollectionCitizenLogEntity", "CollectionCitizenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Voting.ECollecting.Shared.Domain.Entities.CollectionBaseEntity", "Collection")
                        .WithMany("CitizenLogs")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Voting.ECollecting.Shared.Domain.Entities.DecreeEntity", null)
                        .WithMany("CollectionCitizenLogs")
                        .HasForeignKey("DecreeEntityId");

                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("CollectionCitizenLogEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CreatedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("CreatedById")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedById")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByName")
                                .HasColumnType("text");

                            b1.HasKey("CollectionCitizenLogEntityId");

                            b1.ToTable("CollectionCitizenLogs");

                            b1.WithOwner()
                                .HasForeignKey("CollectionCitizenLogEntityId");
                        });

                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.IntegritySignature.IntegritySignatureInfo", "IntegritySignatureInfo", b1 =>
                        {
                            b1.Property<Guid>("CollectionCitizenLogEntityId")
                                .HasColumnType("uuid");

                            b1.Property<byte[]>("IntegritySignature")
                                .IsRequired()
                                .HasColumnType("bytea");

                            b1.Property<string>("IntegritySignatureKeyId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<byte>("IntegritySignatureVersion")
                                .HasColumnType("smallint");

                            b1.HasKey("CollectionCitizenLogEntityId");

                            b1.ToTable("CollectionCitizenLogs");

                            b1.WithOwner()
                                .HasForeignKey("CollectionCitizenLogEntityId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("CollectionCitizen");

                    b.Navigation("IntegritySignatureInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.CollectionCountEntity", b =>
                {
                    b.HasOne("Voting.ECollecting.Shared.Domain.Entities.CollectionBaseEntity", "Collection")
                        .WithOne("CollectionCount")
                        .HasForeignKey("Voting.ECollecting.Shared.Domain.Entities.CollectionCountEntity", "CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("CollectionCountEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CreatedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("CreatedById")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedById")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByName")
                                .HasColumnType("text");

                            b1.HasKey("CollectionCountEntityId");

                            b1.ToTable("CollectionCounts");

                            b1.WithOwner()
                                .HasForeignKey("CollectionCountEntityId");
                        });

                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.IntegritySignature.IntegritySignatureInfo", "IntegritySignatureInfo", b1 =>
                        {
                            b1.Property<Guid>("CollectionCountEntityId")
                                .HasColumnType("uuid");

                            b1.Property<byte[]>("IntegritySignature")
                                .IsRequired()
                                .HasColumnType("bytea");

                            b1.Property<string>("IntegritySignatureKeyId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<byte>("IntegritySignatureVersion")
                                .HasColumnType("smallint");

                            b1.HasKey("CollectionCountEntityId");

                            b1.ToTable("CollectionCounts");

                            b1.WithOwner()
                                .HasForeignKey("CollectionCountEntityId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("IntegritySignatureInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.CollectionMessageEntity", b =>
                {
                    b.HasOne("Voting.ECollecting.Shared.Domain.Entities.CollectionBaseEntity", "Collection")
                        .WithMany("Messages")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("CollectionMessageEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CreatedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("CreatedById")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedById")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByName")
                                .HasColumnType("text");

                            b1.HasKey("CollectionMessageEntityId");

                            b1.ToTable("CollectionMessages");

                            b1.WithOwner()
                                .HasForeignKey("CollectionMessageEntityId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.CollectionMunicipalityEntity", b =>
                {
                    b.HasOne("Voting.ECollecting.Shared.Domain.Entities.CollectionBaseEntity", "Collection")
                        .WithMany("Municipalities")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("CollectionMunicipalityEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CreatedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("CreatedById")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedById")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByName")
                                .HasColumnType("text");

                            b1.HasKey("CollectionMunicipalityEntityId");

                            b1.ToTable("CollectionMunicipalities");

                            b1.WithOwner()
                                .HasForeignKey("CollectionMunicipalityEntityId");
                        });

                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.CollectionSignatureSheetCount", "PhysicalCount", b1 =>
                        {
                            b1.Property<Guid>("CollectionMunicipalityEntityId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Invalid")
                                .HasColumnType("integer");

                            b1.Property<int>("Valid")
                                .HasColumnType("integer");

                            b1.HasKey("CollectionMunicipalityEntityId");

                            b1.ToTable("CollectionMunicipalities");

                            b1.WithOwner()
                                .HasForeignKey("CollectionMunicipalityEntityId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("PhysicalCount")
                        .IsRequired();
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.CollectionPermissionEntity", b =>
                {
                    b.HasOne("Voting.ECollecting.Shared.Domain.Entities.CollectionBaseEntity", "Collection")
                        .WithMany("Permissions")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Voting.ECollecting.Shared.Domain.Entities.InitiativeCommitteeMemberEntity", "InitiativeCommitteeMember")
                        .WithOne("Permission")
                        .HasForeignKey("Voting.ECollecting.Shared.Domain.Entities.CollectionPermissionEntity", "InitiativeCommitteeMemberId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("CollectionPermissionEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CreatedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("CreatedById")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedById")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByName")
                                .HasColumnType("text");

                            b1.HasKey("CollectionPermissionEntityId");

                            b1.ToTable("CollectionPermissions");

                            b1.WithOwner()
                                .HasForeignKey("CollectionPermissionEntityId");
                        });

                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.IntegritySignature.IntegritySignatureInfo", "IntegritySignatureInfo", b1 =>
                        {
                            b1.Property<Guid>("CollectionPermissionEntityId")
                                .HasColumnType("uuid");

                            b1.Property<byte[]>("IntegritySignature")
                                .IsRequired()
                                .HasColumnType("bytea");

                            b1.Property<string>("IntegritySignatureKeyId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<byte>("IntegritySignatureVersion")
                                .HasColumnType("smallint");

                            b1.HasKey("CollectionPermissionEntityId");

                            b1.ToTable("CollectionPermissions");

                            b1.WithOwner()
                                .HasForeignKey("CollectionPermissionEntityId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("InitiativeCommitteeMember");

                    b.Navigation("IntegritySignatureInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.CollectionSignatureSheetEntity", b =>
                {
                    b.HasOne("Voting.ECollecting.Shared.Domain.Entities.CollectionMunicipalityEntity", "CollectionMunicipality")
                        .WithMany("SignatureSheets")
                        .HasForeignKey("CollectionMunicipalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("CollectionSignatureSheetEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CreatedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("CreatedById")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedById")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByName")
                                .HasColumnType("text");

                            b1.HasKey("CollectionSignatureSheetEntityId");

                            b1.ToTable("CollectionSignatureSheets");

                            b1.WithOwner()
                                .HasForeignKey("CollectionSignatureSheetEntityId");
                        });

                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.CollectionSignatureSheetCount", "Count", b1 =>
                        {
                            b1.Property<Guid>("CollectionSignatureSheetEntityId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Invalid")
                                .HasColumnType("integer");

                            b1.Property<int>("Valid")
                                .HasColumnType("integer");

                            b1.HasKey("CollectionSignatureSheetEntityId");

                            b1.ToTable("CollectionSignatureSheets");

                            b1.WithOwner()
                                .HasForeignKey("CollectionSignatureSheetEntityId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("CollectionMunicipality");

                    b.Navigation("Count")
                        .IsRequired();
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.DecreeEntity", b =>
                {
                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("DecreeEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CreatedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("CreatedById")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedById")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByName")
                                .HasColumnType("text");

                            b1.HasKey("DecreeEntityId");

                            b1.ToTable("Decrees");

                            b1.WithOwner()
                                .HasForeignKey("DecreeEntityId");
                        });

                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.IntegritySignature.IntegritySignatureInfo", "IntegritySignatureInfo", b1 =>
                        {
                            b1.Property<Guid>("DecreeEntityId")
                                .HasColumnType("uuid");

                            b1.Property<byte[]>("IntegritySignature")
                                .IsRequired()
                                .HasColumnType("bytea");

                            b1.Property<string>("IntegritySignatureKeyId")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<byte>("IntegritySignatureVersion")
                                .HasColumnType("smallint");

                            b1.HasKey("DecreeEntityId");

                            b1.ToTable("Decrees");

                            b1.WithOwner()
                                .HasForeignKey("DecreeEntityId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("IntegritySignatureInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.DomainOfInfluenceEntity", b =>
                {
                    b.HasOne("Voting.ECollecting.Shared.Domain.Entities.FileEntity", "Logo")
                        .WithOne("LogoOfDomainOfInfluence")
                        .HasForeignKey("Voting.ECollecting.Shared.Domain.Entities.DomainOfInfluenceEntity", "LogoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("DomainOfInfluenceEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CreatedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("CreatedById")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedById")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByName")
                                .HasColumnType("text");

                            b1.HasKey("DomainOfInfluenceEntityId");

                            b1.ToTable("DomainOfInfluences");

                            b1.WithOwner()
                                .HasForeignKey("DomainOfInfluenceEntityId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("Logo");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.FileContentEntity", b =>
                {
                    b.HasOne("Voting.ECollecting.Shared.Domain.Entities.FileEntity", "File")
                        .WithOne("Content")
                        .HasForeignKey("Voting.ECollecting.Shared.Domain.Entities.FileContentEntity", "FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.FileEntity", b =>
                {
                    b.HasOne("Voting.ECollecting.Shared.Domain.Entities.InitiativeEntity", "CommitteeListOfInitiative")
                        .WithMany("CommitteeLists")
                        .HasForeignKey("CommitteeListOfInitiativeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("FileEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CreatedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("CreatedById")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedById")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByName")
                                .HasColumnType("text");

                            b1.HasKey("FileEntityId");

                            b1.ToTable("Files");

                            b1.WithOwner()
                                .HasForeignKey("FileEntityId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("CommitteeListOfInitiative");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.ImportStatisticEntity", b =>
                {
                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("ImportStatisticEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CreatedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("CreatedById")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedById")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByName")
                                .HasColumnType("text");

                            b1.HasKey("ImportStatisticEntityId");

                            b1.ToTable("ImportStatistics");

                            b1.WithOwner()
                                .HasForeignKey("ImportStatisticEntityId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.InitiativeCommitteeMemberEntity", b =>
                {
                    b.HasOne("Voting.ECollecting.Shared.Domain.Entities.InitiativeEntity", "Initiative")
                        .WithMany("CommitteeMembers")
                        .HasForeignKey("InitiativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Voting.ECollecting.Shared.Domain.Entities.FileEntity", "SignatureFile")
                        .WithOne("SignatureSheetOfInitiativeCommitteeMember")
                        .HasForeignKey("Voting.ECollecting.Shared.Domain.Entities.InitiativeCommitteeMemberEntity", "SignatureFileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.Audit.AuditInfo", "AuditInfo", b1 =>
                        {
                            b1.Property<Guid>("InitiativeCommitteeMemberEntityId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("CreatedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("CreatedById")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("CreatedByName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<DateTime?>("ModifiedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("ModifiedByEmail")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedById")
                                .HasColumnType("text");

                            b1.Property<string>("ModifiedByName")
                                .HasColumnType("text");

                            b1.HasKey("InitiativeCommitteeMemberEntityId");

                            b1.ToTable("InitiativeCommitteeMembers");

                            b1.WithOwner()
                                .HasForeignKey("InitiativeCommitteeMemberEntityId");
                        });

                    b.Navigation("AuditInfo")
                        .IsRequired();

                    b.Navigation("Initiative");

                    b.Navigation("SignatureFile");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.UserNotificationEntity", b =>
                {
                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.UserNotificationTemplateBag", "TemplateBag", b1 =>
                        {
                            b1.Property<Guid>("UserNotificationEntityId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("CollectionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CollectionName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int?>("CollectionType")
                                .HasColumnType("integer");

                            b1.Property<Guid?>("DecreeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("DecreeName")
                                .HasColumnType("text");

                            b1.Property<int>("NotificationType")
                                .HasColumnType("integer");

                            b1.Property<bool>("RecipientIsCitizen")
                                .HasColumnType("boolean");

                            b1.HasKey("UserNotificationEntityId");

                            b1.ToTable("UserNotifications");

                            b1.WithOwner()
                                .HasForeignKey("UserNotificationEntityId");
                        });

                    b.Navigation("TemplateBag")
                        .IsRequired();
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.InitiativeEntity", b =>
                {
                    b.HasOne("Voting.ECollecting.Shared.Domain.Entities.InitiativeSubTypeEntity", "SubType")
                        .WithMany()
                        .HasForeignKey("SubTypeId");

                    b.OwnsOne("Voting.ECollecting.Shared.Domain.Entities.InitiativeLockedFields", "LockedFields", b1 =>
                        {
                            b1.Property<Guid>("InitiativeEntityId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("Description")
                                .HasColumnType("boolean");

                            b1.Property<bool>("Wording")
                                .HasColumnType("boolean");

                            b1.HasKey("InitiativeEntityId");

                            b1.ToTable("Collections");

                            b1.WithOwner()
                                .HasForeignKey("InitiativeEntityId");
                        });

                    b.Navigation("LockedFields")
                        .IsRequired();

                    b.Navigation("SubType");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.ReferendumEntity", b =>
                {
                    b.HasOne("Voting.ECollecting.Shared.Domain.Entities.DecreeEntity", "Decree")
                        .WithMany("Collections")
                        .HasForeignKey("DecreeId");

                    b.Navigation("Decree");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.AccessControlListDoiEntity", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.CollectionBaseEntity", b =>
                {
                    b.Navigation("CitizenLogs");

                    b.Navigation("CollectionCount");

                    b.Navigation("Messages");

                    b.Navigation("Municipalities");

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.CollectionCitizenEntity", b =>
                {
                    b.Navigation("Log");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.CollectionMunicipalityEntity", b =>
                {
                    b.Navigation("Citizens");

                    b.Navigation("SignatureSheets");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.CollectionSignatureSheetEntity", b =>
                {
                    b.Navigation("Citizens");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.DecreeEntity", b =>
                {
                    b.Navigation("CollectionCitizenLogs");

                    b.Navigation("Collections");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.FileEntity", b =>
                {
                    b.Navigation("Content");

                    b.Navigation("ContentOfCertificate");

                    b.Navigation("ImageOfCollection");

                    b.Navigation("LogoOfCollection");

                    b.Navigation("LogoOfDomainOfInfluence");

                    b.Navigation("SignatureSheetOfCollection");

                    b.Navigation("SignatureSheetOfInitiativeCommitteeMember");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.ImportStatisticEntity", b =>
                {
                    b.Navigation("AccessControlListDois");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.InitiativeCommitteeMemberEntity", b =>
                {
                    b.Navigation("Permission");
                });

            modelBuilder.Entity("Voting.ECollecting.Shared.Domain.Entities.InitiativeEntity", b =>
                {
                    b.Navigation("CommitteeLists");

                    b.Navigation("CommitteeMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
