//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voting.ECollecting.Admin.Core.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Voting.ECollecting.Admin.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string UserNotification_LogoDeleted {
            get {
                return ResourceManager.GetString("UserNotification.LogoDeleted", resourceCulture);
            }
        }
        
        internal static string UserNotification_ImageDeleted {
            get {
                return ResourceManager.GetString("UserNotification.ImageDeleted", resourceCulture);
            }
        }
        
        internal static string UserNotification_SignatureSheetDeleted {
            get {
                return ResourceManager.GetString("UserNotification.SignatureSheetDeleted", resourceCulture);
            }
        }
        
        internal static string SecondFactorTransaction_DeleteInitiative {
            get {
                return ResourceManager.GetString("SecondFactorTransaction.DeleteInitiative", resourceCulture);
            }
        }
        
        internal static string SecondFactorTransaction_DeleteDecree {
            get {
                return ResourceManager.GetString("SecondFactorTransaction.DeleteDecree", resourceCulture);
            }
        }
        
        internal static string UserNotification_GeneralInformationChanged {
            get {
                return ResourceManager.GetString("UserNotification.GeneralInformationChanged", resourceCulture);
            }
        }
        
        internal static string UserNotification_CommitteeMemberUpdated {
            get {
                return ResourceManager.GetString("UserNotification.CommitteeMemberUpdated", resourceCulture);
            }
        }
        
        internal static string InitiativeCommitteeMemberFields_PoliticalFirstName {
            get {
                return ResourceManager.GetString("InitiativeCommitteeMemberFields.PoliticalFirstName", resourceCulture);
            }
        }
        
        internal static string InitiativeCommitteeMemberFields_PoliticalLastName {
            get {
                return ResourceManager.GetString("InitiativeCommitteeMemberFields.PoliticalLastName", resourceCulture);
            }
        }
        
        internal static string InitiativeCommitteeMemberFields_PoliticalResidence {
            get {
                return ResourceManager.GetString("InitiativeCommitteeMemberFields.PoliticalResidence", resourceCulture);
            }
        }
        
        internal static string InitiativeCommitteeMemberFields_PoliticalDuty {
            get {
                return ResourceManager.GetString("InitiativeCommitteeMemberFields.PoliticalDuty", resourceCulture);
            }
        }
        
        internal static string DomainOfInfluenceName_Ch {
            get {
                return ResourceManager.GetString("DomainOfInfluenceName.Ch", resourceCulture);
            }
        }
        
        internal static string DomainOfInfluenceName_Ct {
            get {
                return ResourceManager.GetString("DomainOfInfluenceName.Ct", resourceCulture);
            }
        }
        
        internal static string ReferendumFields_Description {
            get {
                return ResourceManager.GetString("ReferendumFields.Description", resourceCulture);
            }
        }
        
        internal static string ReferendumFields_Reason {
            get {
                return ResourceManager.GetString("ReferendumFields.Reason", resourceCulture);
            }
        }
        
        internal static string ReferendumFields_MembersCommittee {
            get {
                return ResourceManager.GetString("ReferendumFields.MembersCommittee", resourceCulture);
            }
        }
        
        internal static string ReferendumFields_Link {
            get {
                return ResourceManager.GetString("ReferendumFields.Link", resourceCulture);
            }
        }
        
        internal static string ReferendumFields_Address {
            get {
                return ResourceManager.GetString("ReferendumFields.Address", resourceCulture);
            }
        }
        
        internal static string InitiativeFields_Description {
            get {
                return ResourceManager.GetString("InitiativeFields.Description", resourceCulture);
            }
        }
        
        internal static string InitiativeFields_Wording {
            get {
                return ResourceManager.GetString("InitiativeFields.Wording", resourceCulture);
            }
        }
        
        internal static string InitiativeFields_Reason {
            get {
                return ResourceManager.GetString("InitiativeFields.Reason", resourceCulture);
            }
        }
        
        internal static string InitiativeFields_Address {
            get {
                return ResourceManager.GetString("InitiativeFields.Address", resourceCulture);
            }
        }
    }
}
