//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voting.ECollecting.Admin.Core.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Voting.ECollecting.Admin.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string UserNotification_LogoDeleted {
            get {
                return ResourceManager.GetString("UserNotification.LogoDeleted", resourceCulture);
            }
        }
        
        internal static string UserNotification_ImageDeleted {
            get {
                return ResourceManager.GetString("UserNotification.ImageDeleted", resourceCulture);
            }
        }
        
        internal static string UserNotification_SignatureSheetDeleted {
            get {
                return ResourceManager.GetString("UserNotification.SignatureSheetDeleted", resourceCulture);
            }
        }
        
        internal static string SecondFactorTransaction_DeleteInitiative {
            get {
                return ResourceManager.GetString("SecondFactorTransaction.DeleteInitiative", resourceCulture);
            }
        }
        
        internal static string SecondFactorTransaction_DeleteDecree {
            get {
                return ResourceManager.GetString("SecondFactorTransaction.DeleteDecree", resourceCulture);
            }
        }
    }
}
