//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voting.ECollecting.Citizen.Core.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Voting.ECollecting.Citizen.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string UserNotification_AccessibilityMessage_NoData {
            get {
                return ResourceManager.GetString("UserNotification.AccessibilityMessage.NoData", resourceCulture);
            }
        }
        
        internal static string UserNotification_AccessibilityMessage_Salutation_Mr {
            get {
                return ResourceManager.GetString("UserNotification.AccessibilityMessage.Salutation.Mr", resourceCulture);
            }
        }
        
        internal static string UserNotification_AccessibilityMessage_Salutation_Mrs {
            get {
                return ResourceManager.GetString("UserNotification.AccessibilityMessage.Salutation.Mrs", resourceCulture);
            }
        }
        
        internal static string UserNotification_AccessibilityMessage_Category_Problem {
            get {
                return ResourceManager.GetString("UserNotification.AccessibilityMessage.Category.Problem", resourceCulture);
            }
        }
        
        internal static string UserNotification_AccessibilityMessage_Category_OptimisationProposal {
            get {
                return ResourceManager.GetString("UserNotification.AccessibilityMessage.Category.OptimisationProposal", resourceCulture);
            }
        }
        
        internal static string UserNotification_AccessibilityMessage_Category_Request {
            get {
                return ResourceManager.GetString("UserNotification.AccessibilityMessage.Category.Request", resourceCulture);
            }
        }
        
        internal static string UserNotification_AccessibilityMessage_Category_Various {
            get {
                return ResourceManager.GetString("UserNotification.AccessibilityMessage.Category.Various", resourceCulture);
            }
        }
    }
}
